parameters:
#    lorem_app.example.class: Lorem\Bundle\AppBundle\Example

services:
#    lorem_app.example:
#        class: %lorem_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
