parameters:
#    dada_test.example.class: Dada\TestBundle\Example

services:

    # News
    dada_test_news_admin:
        class: Dada\TestBundle\Admin\NewsAdmin
        arguments: [ @dada_test.news_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    dada_test.news_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Dada\TestBundle\Entity\News ]
        parent: msi_cmf.manager
